import type {
  AutomationSettings,
  DashboardSnapshot,
  FeatureCard,
  ValuableItemBudgets,
} from "../types/contracts";

export const zeroBudgets: ValuableItemBudgets = {
  fieldDice: 0,
  glitter: 0,
  eggs: 0,
  stickers: 0,
  vouchers: 0,
  shrineDonations: 0,
};

const safeSettings: AutomationSettings = {
  features: {
    collect: true,
    bosses: true,
    vicious: false,
    memory: true,
    "field-boost": true,
    nectar: true,
    hotbar: false,
    "brown-bear": true,
    "science-bear": true,
    "polar-bear": true,
    "bucko-riley": false,
    "planter-cycle": true,
    pesticide: true,
    tacky: true,
  },
  gathering: {
    enabled: true,
    fields: ["Pine Tree Forest", "Mushroom Field", "Clover Field"],
    pattern: "e_lol",
    minutesPerField: 12,
    returnAtCapacity: 95,
    driftCorrection: true,
  },
  safety: {
    pauseOnFocusLoss: true,
    requireForeground: true,
    confirmHighRiskActions: true,
    budgets: zeroBudgets,
  },
  recovery: {
    reconnectEnabled: true,
    maxAttempts: 5,
    deadlineMinutes: 15,
    restartOnConfirmedFreeze: false,
  },
  monitoring: {
    discordEnabled: false,
    evidenceRetentionDays: 14,
    evidenceLimitMb: 250,
    permissions: {
      status: false,
      macroControl: false,
      settings: false,
      screenshots: false,
      remoteInput: false,
      extensionImport: false,
      systemPower: false,
    },
  },
  hotkeys: {
    start: "F1",
    pause: "F2",
    stop: "F3",
    emergencyStop: "Ctrl+Shift+F12",
  },
};

const features: FeatureCard[] = [
  {
    id: "collect",
    title: "Daily collections",
    description: "Dispensers, boosters, wealth clock, and free treats.",
    enabled: true,
    status: "7 routes ready",
    category: "activity",
  },
  {
    id: "bosses",
    title: "Boss runs",
    description: "King Beetle, Tunnel Bear, Coconut Crab, and Stump Snail.",
    enabled: true,
    status: "2 available",
    category: "activity",
  },
  {
    id: "vicious",
    title: "Vicious Bee hunt",
    description: "Search known spawn fields with bounded night checks.",
    enabled: false,
    status: "Off",
    category: "activity",
  },
  {
    id: "memory",
    title: "Memory matches",
    description: "Solve enabled memory games when cooldowns are ready.",
    enabled: true,
    status: "In 42m",
    category: "activity",
  },
  {
    id: "field-boost",
    title: "Field boosters",
    description: "Use boosters while respecting valuable-item budgets.",
    enabled: true,
    status: "Budget safe",
    category: "boost",
  },
  {
    id: "nectar",
    title: "Nectar upkeep",
    description: "Balance planter nectar before long gathering cycles.",
    enabled: true,
    status: "84% avg",
    category: "boost",
  },
  {
    id: "hotbar",
    title: "Hotbar schedule",
    description: "Timed consumables with explicit per-item limits.",
    enabled: false,
    status: "No item budget",
    category: "boost",
  },
  {
    id: "science-bear",
    title: "Science Bear",
    description:
      "Plan all 31 permanent quests with overlap scoring and Translator milestones.",
    enabled: true,
    status: "3 Translator milestones",
    category: "quest",
  },
  {
    id: "brown-bear",
    title: "Brown Bear",
    description: "Detect and complete supported pollen quests.",
    enabled: true,
    status: "Pine Tree pollen",
    category: "quest",
  },
  {
    id: "polar-bear",
    title: "Polar Bear",
    description: "Track mob and ingredient requirements.",
    enabled: true,
    status: "2 / 3 tasks",
    category: "quest",
  },
  {
    id: "bucko-riley",
    title: "Bucko & Riley",
    description: "Prioritize color pollen and matching fields.",
    enabled: false,
    status: "Off",
    category: "quest",
  },
  {
    id: "planter-cycle",
    title: "Planter cycle",
    description: "Harvest and replant from a validated field rotation.",
    enabled: true,
    status: "Next in 18m",
    category: "planter",
  },
  {
    id: "pesticide",
    title: "Pesticide planter",
    description: "Pine Tree Forest · harvest at 100%.",
    enabled: true,
    status: "72% grown",
    category: "planter",
  },
  {
    id: "tacky",
    title: "Tacky planter",
    description: "Sunflower Field · harvest at 95%.",
    enabled: true,
    status: "48% grown",
    category: "planter",
  },
];

export function createMockSnapshot(): DashboardSnapshot {
  const now = Date.now();
  return {
    runId: null,
    runState: "Idle",
    runStateReason: "Ready to start",
    activeProfileId: "01900000-0000-7000-8000-000000000001",
    onboardingComplete: true,
    safeMode: false,
    profiles: [
      {
        id: "01900000-0000-7000-8000-000000000001",
        name: "Main hive",
        description: "Balanced blue gathering",
        accent: "#f4b942",
        lastUsedAt: new Date(now - 60_000).toISOString(),
        settings: structuredClone(safeSettings),
      },
      {
        id: "night",
        name: "Night run",
        description: "Mobs, bosses, and Vicious Bee",
        accent: "#8a7cf1",
        lastUsedAt: new Date(now - 86_400_000).toISOString(),
        settings: {
          ...structuredClone(safeSettings),
          gathering: {
            ...safeSettings.gathering,
            fields: ["Cactus Field", "Rose Field"],
            minutesPerField: 8,
          },
        },
      },
      {
        id: "01900000-0000-7000-8000-000000000002",
        name: "Safe test",
        description: "No purchases, donations, or item use",
        accent: "#58b889",
        lastUsedAt: new Date(now - 172_800_000).toISOString(),
        settings: {
          ...structuredClone(safeSettings),
          recovery: {
            ...safeSettings.recovery,
            restartOnConfirmedFreeze: false,
          },
        },
      },
    ],
    session: {
      connected: true,
      processName: "RobloxPlayerBeta.exe",
      pid: 18472,
      windowTitle: "Roblox",
      resolution: "1920 × 1080",
      dpi: 100,
      foreground: true,
      calibration: "high",
    },
    readiness: [
      {
        id: "roblox",
        label: "Roblox client",
        detail: "Official client · PID 18472",
        status: "ready",
      },
      {
        id: "window",
        label: "Window calibration",
        detail: "1920 × 1080 at 100% · high confidence",
        status: "ready",
      },
      {
        id: "hive",
        label: "Hive and spawn",
        detail: "Hive slot will be verified at start",
        status: "warning",
        actionLabel: "Review",
      },
      {
        id: "budget",
        label: "Item safeguards",
        detail: "All valuable-item budgets are zero",
        status: "ready",
      },
    ],
    metrics: [
      {
        id: "honey",
        label: "Honey this session",
        value: "12.8B",
        delta: "+8.4% / hr",
        tone: "gold",
      },
      {
        id: "rate",
        label: "Current rate",
        value: "2.14B/h",
        delta: "Stable",
        tone: "green",
      },
      {
        id: "uptime",
        label: "Last run",
        value: "3h 42m",
        delta: "No recoveries",
        tone: "blue",
      },
      {
        id: "bag",
        label: "Bag estimate",
        value: "68%",
        delta: "Return at 95%",
        tone: "neutral",
      },
    ],
    timeline: [
      {
        id: "t1",
        timestamp: new Date(now - 12 * 60_000).toISOString(),
        title: "Settings validated",
        detail: "Main hive profile is ready",
        tone: "success",
      },
      {
        id: "t2",
        timestamp: new Date(now - 27 * 60_000).toISOString(),
        title: "Pesticide planter checked",
        detail: "72% grown in Pine Tree Forest",
        tone: "info",
      },
      {
        id: "t3",
        timestamp: new Date(now - 54 * 60_000).toISOString(),
        title: "Session stopped",
        detail: "Normal stop · all inputs released",
        tone: "info",
      },
      {
        id: "t4",
        timestamp: new Date(now - 3 * 3_600_000).toISOString(),
        title: "Focus changed",
        detail: "Paused for 8 seconds and resumed safely",
        tone: "warning",
      },
    ],
    queue: [
      {
        id: "q1",
        label: "Gather pollen",
        detail: "Pine Tree Forest · e_lol · 12 min",
        status: "next",
        confidence: 0.98,
      },
      {
        id: "q2",
        label: "Return to hive",
        detail: "At 95% capacity or after 12 min",
        status: "queued",
      },
      {
        id: "q3",
        label: "Pesticide planter",
        detail: "Check growth, harvest at 100%",
        status: "queued",
        confidence: 0.91,
      },
      {
        id: "q4",
        label: "Wealth clock",
        detail: "Available in 42 min",
        status: "queued",
      },
    ],
    features,
    extensions: [
      {
        id: "core-patterns",
        name: "NectarPilot patterns",
        author: "NectarPilot",
        version: "0.1.0",
        description: "Built-in validated gathering patterns and routes.",
        digest: "sha256:7fe6…52ad",
        trust: "built_in",
        permissions: ["Read detections", "Submit movement plan"],
        enabled: true,
      },
      {
        id: "legacy:pattern:patterns/e_lol.ahk",
        name: "Cactus spiral (legacy)",
        author: "Imported from Natro Macro",
        version: "1.1.2",
        description: "Legacy AHK pattern requiring the compatibility runner.",
        digest: "sha256:9a14…e2c8",
        trust: "review_required",
        permissions: ["Legacy AHK runner", "Keyboard input", "Mouse input"],
        enabled: false,
      },
      {
        id: "unsafe-pack",
        name: "Unknown route pack",
        author: "Unknown publisher",
        version: "0.3.1",
        description: "Digest changed since the last review.",
        digest: "sha256:22bd…f103",
        trust: "blocked",
        permissions: ["Legacy AHK runner", "Network access"],
        enabled: false,
      },
    ],
    logs: [
      {
        id: "l1",
        timestamp: new Date(now - 20_000).toISOString(),
        level: "info",
        component: "session",
        message: "Foreground window ownership verified for PID 18472",
      },
      {
        id: "l2",
        timestamp: new Date(now - 34_000).toISOString(),
        level: "debug",
        component: "vision",
        message: "Anchor consensus 4/4, confidence 0.98",
      },
      {
        id: "l3",
        timestamp: new Date(now - 2 * 60_000).toISOString(),
        level: "warning",
        component: "scheduler",
        message: "Hive claim verification deferred until preflight",
      },
      {
        id: "l4",
        timestamp: new Date(now - 7 * 60_000).toISOString(),
        level: "info",
        component: "config",
        message: "Primary profile passed schema validation",
      },
      {
        id: "l5",
        timestamp: new Date(now - 22 * 60_000).toISOString(),
        level: "debug",
        component: "evidence",
        message: "Retention usage 18 MB of 250 MB",
      },
    ],
    updatedAt: new Date().toISOString(),
  };
}
