// This file has been generated by Specta. DO NOT EDIT.

export type ActionOutcome = "succeeded" | "skipped" | "cancelled" | "failed" | "needs_attention"

export type ActionResult = { action: string; outcome: ActionOutcome; started_at: string; finished_at: string; message: string; details?: JsonValue }

export type AutomationConfig = { gathering_enabled: boolean; reconnect_enabled: boolean; rotations: FieldRotation[]; features: FeatureFlags; hotkeys: HotkeyConfig; session: SessionConfig;
/**
 * Manual planter reminders; the desktop shows countdowns and due badges.
 * Nothing is placed or collected automatically from these entries.
 */
planters: ManualPlanterTimer[];
/**
 * Allowlisted clock, free-dispenser, and field-booster routes run at cycle
 * boundaries during orchestrated sessions. Valuable and state-changing
 * routes are never accepted by this scheduler.
 */
collect: CollectTask[] }

/**
 * One cooldown-scheduled allowlisted target, e.g. `clock` every 240 minutes.
 */
export type CollectTask = {
/**
 * Approved clock/dispenser/booster name. The engine maps this onto an
 * exact manifest route and requires that route's trusted digest.
 */
target: string; cooldown_minutes: number }

export type Command = { type: "start"; payload: { mode: StartMode } } | { type: "pause" } | { type: "resume" } | { type: "stop" } | { type: "emergency_stop" } |
/**
 * Internal desktop-to-daemon lifecycle request. It performs the same
 * fail-safe input release as an emergency stop before process exit.
 */
{ type: "shutdown_daemon" } | { type: "get_snapshot" } | { type: "get_profiles" } | { type: "select_profile" } |
/**
 * Runs one manifest-pinned legacy `AutoHotkey` asset through the daemon's
 * contained compatibility port. The daemon re-checks both this digest and
 * the profile's stored hash-bound consent before process creation.
 */
{ type: "start_legacy"; payload: { script_id: string; approved_sha256: string } } |
/**
 * Runs the profile's configured field rotation as an orchestrated loop of
 * trusted legacy assets (travel, gather pattern, reset/convert), bounded
 * by cycle and wall-clock limits. Every referenced asset must already be
 * hash-trusted in the profile.
 */
{ type: "start_legacy_session"; payload: { max_cycles: number; max_minutes: number } } |
/**
 * Returns the exact generated harness for one manifest-pinned asset so a
 * user can review what would run before trusting or starting it.
 */
{ type: "inspect_legacy"; payload: { script_id: string } } |
/**
 * Stores one named secret (for example the private-server link) in the
 * daemon's encrypted store. The value never appears in events or logs.
 */
{ type: "import_secret"; payload: { name: string; value: string } } | { type: "get_run_history" } |
/**
 * Opens the in-game quest log from the client-anchored legacy menu
 * position, verifies the open state, reads the giver icon, title, and
 * objective bars, then closes it. Requires an idle engine and one
 * foreground Roblox client; uncertain readings are reported, not guessed.
 */
{ type: "scan_quests" } | { type: "save_profile"; payload: { profile: Profile } } | { type: "delete_profile" } | { type: "export_profile" } | { type: "acknowledge_attention" }

export type CommandEnvelope = { protocol_version: number; request_id: string; profile_id: string; command: Command }

export type DaemonEvent = { type: "command_accepted"; payload: { request_id: string } } | { type: "command_rejected"; payload: { request_id: string; reason: string } } | { type: "state_changed"; payload: { previous: RunState; current: RunState; reason: string } } | { type: "action_completed"; payload: ActionResult } | { type: "reconnect_progress"; payload: ReconnectProgress } | { type: "log"; payload: { level: EventLevel; target: string; message: string; fields?: JsonValue } } | { type: "snapshot"; payload: RunSnapshot } | { type: "profile_saved"; payload: { profile_id: string } } | { type: "profiles"; payload: { profiles: Profile[]; selected_profile_id: string } } | { type: "profile_selected"; payload: { profile_id: string } } | { type: "profile_deleted"; payload: { profile_id: string } } | { type: "profile_exported"; payload: { profile_id: string; json: string } } | { type: "safe_mode_entered"; payload: { crash_count: number; window_seconds: number } } |
/**
 * Final acknowledgement after input cleanup. The daemon flushes this
 * event before a requested graceful process exit.
 */
{ type: "shutdown_ready"; payload: { request_id: string } } |
/**
 * Progress through an orchestrated legacy session plan.
 */
{ type: "session_progress"; payload: SessionProgress } |
/**
 * Review payload for one manifest-pinned legacy asset.
 */
{ type: "legacy_inspection"; payload: LegacyInspection } |
/**
 * Confirmation that a named secret was stored; the value is never echoed.
 */
{ type: "secret_stored"; payload: { name: string } } | { type: "run_history"; payload: {
/**
 * Profile whose records were requested. This lets consumers reject
 * delayed responses after the active profile changes.
 */
profile_id: string; entries: RunRecord[] } } |
/**
 * Passive screen-derived statistics. `None` fields mean the reading was
 * not confident; they are never guessed.
 */
{ type: "stats_sample"; payload: StatsSample } |
/**
 * Advisory quest-log reading. Absent fields mean that part of the log
 * could not be read confidently.
 */
{ type: "quest_scan"; payload: QuestScanResult }

/**
 * A detector result that makes uncertainty impossible to confuse with a value.
 *
 * Callers must use [`Detection::actionable`] to obtain an automation target.
 * `NotFound`, `Uncertain`, malformed confidence values, and `Error` always
 * return `None`.
 */
export type Detection<T> = { status: "found"; value: T; confidence: number; evidence: DetectionEvidence } | { status: "not_found"; evidence: DetectionEvidence } | { status: "uncertain"; reason: string; evidence: DetectionEvidence } | { status: "error"; code: string; message: string; evidence?: DetectionEvidence | null }

export type DetectionEvidence = { detector: string; observed_at: string; region?: NormalizedRegion | null; artifact_id?: string | null; notes: string[] }

export type DiscordConfig = { enabled: boolean;
/**
 * Identifier for a daemon-owned encrypted secret; never the secret itself.
 */
credential_ref: string | null; permissions: DiscordPermissions }

export type DiscordPermissions = { status: boolean; macro_control: boolean; settings: boolean; screenshots: boolean; remote_input: boolean; extension_import: boolean; system_power: boolean }

export type EventEnvelope = { protocol_version: number; sequence: number; run_id: string; timestamp: string; event: DaemonEvent }

export type EventLevel = "trace" | "debug" | "info" | "warn" | "error"

export type FeatureFlags = { collections: boolean; bosses: boolean; vicious_bee: boolean; memory_matches: boolean; quests: boolean; planters: boolean; boosts: boolean; shrine: boolean; stickers: boolean; hotbar_scheduling: boolean; mutations_and_auto_jelly: boolean; seasonal: boolean; custom_extensions: boolean }

export type FieldRotation = { field: string; pattern: string; gather_seconds: number; repetitions?: number }

export type HotkeyConfig = { start: string; pause_resume: string; stop: string; emergency_stop: string }

export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>

export type LegacyInspection = { script_id: string; sha256: string; bytes: number; requires_legacy_bridge: boolean;
/**
 * The complete generated harness that would execute, for human review.
 */
harness_preview: string }

export type LegacySnapshot = { sources: LegacySource[] }

/**
 * Portable data retained from one imported INI file. Secret-like values are
 * redacted during import and remain available only in the untouched source.
 */
export type LegacySource = { file_name: string; sha256: string; sections: Partial<{ [key in string]: Partial<{ [key in string]: string }> }> }

export type ManualPlanterTimer = {
/**
 * Planter slot 1..=3 as shown in game.
 */
slot: number;
/**
 * Free-text description, e.g. "Blue Clay in Bamboo".
 */
label: string; placed_at: string; harvest_at: string }

/**
 * A viewport-relative rectangle. All coordinates must be finite and in `0..=1`.
 */
export type NormalizedRegion = { x: number; y: number; width: number; height: number }

export type Profile = { id: string; schema_version: number; name: string; created_at: string; updated_at: string; automation?: AutomationConfig; safety?: SafetyConfig; discord?: DiscordConfig; onboarding_complete?: boolean;
/**
 * Extension identifier to the exact SHA-256 hash the user approved.
 */
trusted_extensions?: Partial<{ [key in string]: string }>; legacy?: LegacySnapshot | null }

export type QuestScanResult = { scanned_at: string;
/**
 * Detected quest giver (`snake_case`), when the icon match was confident.
 */
giver: string | null; quest_id: string | null; quest_name: string | null;
/**
 * Objective bar completion in screen order; empty when unreadable.
 */
bars_complete: boolean[];
/**
 * Fields that advance the detected quest's incomplete objectives.
 */
recommended_fields: string[];
/**
 * Human-readable uncertainty and held-work explanations.
 */
notes: string[] }

export type ReconnectProgress = { attempt: number; maximum_attempts: number; elapsed_seconds: number; deadline_seconds: number }

export type RunRecord = { run_id: string; profile_id: string;
/**
 * `legacy`, `legacy_session`, or `native`.
 */
kind: string; started_at: string; finished_at: string; final_state: string; summary: string; steps_succeeded: number; steps_failed: number }

export type RunSnapshot = { run_id: string; profile_id: string; state: RunState; safe_mode: boolean; active_task: string | null; last_sequence: number }

export type RunState = "idle" | "preflight" | "running" | "paused" | "recovering" | "needs_attention" | "stopping" | "faulted"

export type SafetyConfig = { item_budgets: ValuableItemBudgets; purchases_enabled: boolean; donations_enabled: boolean; trades_enabled: boolean; allow_system_power: boolean; evidence_retention_days: number; evidence_retention_megabytes: number }

/**
 * Bounds for one orchestrated legacy gather session.
 */
export type SessionConfig = {
/**
 * Seconds to remain at the hive converting after each reset step.
 */
convert_wait_seconds: number; default_max_cycles: number; default_max_minutes: number }

export type SessionProgress = { cycle: number; max_cycles: number; step_index: number; step_count: number; description: string }

export type StartMode = "normal" | "dry_run" | "diagnostics"

export type StatsSample = { sampled_at: string;
/**
 * Current honey read from the HUD counter; absent when OCR agreement
 * was insufficient.
 */
honey: number | null;
/**
 * Windowed rate derived from confident samples only.
 */
honey_per_hour: number | null; session_minutes: number }

/**
 * All valuable consumables are denied until the user sets a positive budget.
 */
export type ValuableItemBudgets = { dice: number; glitter: number; eggs: number; stickers: number; vouchers: number; shrine_donations: number; other: Partial<{ [key in string]: number }> }
