// This file has been generated by Specta. DO NOT EDIT.

export type ActionOutcome = "succeeded" | "skipped" | "cancelled" | "failed" | "needs_attention"

export type ActionResult = { action: string; outcome: ActionOutcome; started_at: string; finished_at: string; message: string; details?: JsonValue }

export type AutomationConfig = { gathering_enabled: boolean; reconnect_enabled: boolean; rotations: FieldRotation[]; features: FeatureFlags; hotkeys: HotkeyConfig }

export type Command = { type: "start"; payload: { mode: StartMode } } | { type: "pause" } | { type: "resume" } | { type: "stop" } | { type: "emergency_stop" } |
/**
 * Internal desktop-to-daemon lifecycle request. It performs the same
 * fail-safe input release as an emergency stop before process exit.
 */
{ type: "shutdown_daemon" } | { type: "get_snapshot" } | { type: "save_profile"; payload: { profile: Profile } } | { type: "delete_profile" } | { type: "export_profile" } | { type: "acknowledge_attention" }

export type CommandEnvelope = { protocol_version: number; request_id: string; profile_id: string; command: Command }

export type DaemonEvent = { type: "command_accepted"; payload: { request_id: string } } | { type: "command_rejected"; payload: { request_id: string; reason: string } } | { type: "state_changed"; payload: { previous: RunState; current: RunState; reason: string } } | { type: "action_completed"; payload: ActionResult } | { type: "reconnect_progress"; payload: ReconnectProgress } | { type: "log"; payload: { level: EventLevel; target: string; message: string; fields?: JsonValue } } | { type: "snapshot"; payload: RunSnapshot } | { type: "profile_saved"; payload: { profile_id: string } } | { type: "profile_deleted"; payload: { profile_id: string } } | { type: "profile_exported"; payload: { profile_id: string; json: string } } | { type: "safe_mode_entered"; payload: { crash_count: number; window_seconds: number } }

/**
 * A detector result that makes uncertainty impossible to confuse with a value.
 *
 * Callers must use [`Detection::actionable`] to obtain an automation target.
 * `NotFound`, `Uncertain`, malformed confidence values, and `Error` always
 * return `None`.
 */
export type Detection<T> = { status: "found"; value: T; confidence: number; evidence: DetectionEvidence } | { status: "not_found"; evidence: DetectionEvidence } | { status: "uncertain"; reason: string; evidence: DetectionEvidence } | { status: "error"; code: string; message: string; evidence?: DetectionEvidence | null }

export type DetectionEvidence = { detector: string; observed_at: string; region?: NormalizedRegion | null; artifact_id?: string | null; notes: string[] }

export type DiscordConfig = { enabled: boolean;
/**
 * Identifier for a daemon-owned encrypted secret; never the secret itself.
 */
credential_ref: string | null; permissions: DiscordPermissions }

export type DiscordPermissions = { status: boolean; macro_control: boolean; settings: boolean; screenshots: boolean; remote_input: boolean; extension_import: boolean; system_power: boolean }

export type EventEnvelope = { protocol_version: number; sequence: number; run_id: string; timestamp: string; event: DaemonEvent }

export type EventLevel = "trace" | "debug" | "info" | "warn" | "error"

export type FeatureFlags = { collections: boolean; bosses: boolean; vicious_bee: boolean; memory_matches: boolean; quests: boolean; planters: boolean; boosts: boolean; shrine: boolean; stickers: boolean; hotbar_scheduling: boolean; mutations_and_auto_jelly: boolean; seasonal: boolean; custom_extensions: boolean }

export type FieldRotation = { field: string; pattern: string; gather_seconds: number; repetitions?: number }

export type HotkeyConfig = { start: string; pause_resume: string; stop: string; emergency_stop: string }

export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>

export type LegacySnapshot = { sources: LegacySource[] }

/**
 * Portable data retained from one imported INI file. Secret-like values are
 * redacted during import and remain available only in the untouched source.
 */
export type LegacySource = { file_name: string; sha256: string; sections: Partial<{ [key in string]: Partial<{ [key in string]: string }> }> }

/**
 * A viewport-relative rectangle. All coordinates must be finite and in `0..=1`.
 */
export type NormalizedRegion = { x: number; y: number; width: number; height: number }

export type Profile = { id: string; schema_version: number; name: string; created_at: string; updated_at: string; automation?: AutomationConfig; safety?: SafetyConfig; discord?: DiscordConfig; onboarding_complete?: boolean;
/**
 * Extension identifier to the exact SHA-256 hash the user approved.
 */
trusted_extensions?: Partial<{ [key in string]: string }>; legacy?: LegacySnapshot | null }

export type ReconnectProgress = { attempt: number; maximum_attempts: number; elapsed_seconds: number; deadline_seconds: number }

export type RunSnapshot = { run_id: string; profile_id: string; state: RunState; safe_mode: boolean; active_task: string | null; last_sequence: number }

export type RunState = "idle" | "preflight" | "running" | "paused" | "recovering" | "needs_attention" | "stopping" | "faulted"

export type SafetyConfig = { item_budgets: ValuableItemBudgets; purchases_enabled: boolean; donations_enabled: boolean; trades_enabled: boolean; allow_system_power: boolean; evidence_retention_days: number; evidence_retention_megabytes: number }

export type StartMode = "normal" | "dry_run" | "diagnostics"

/**
 * All valuable consumables are denied until the user sets a positive budget.
 */
export type ValuableItemBudgets = { dice: number; glitter: number; eggs: number; stickers: number; vouchers: number; shrine_donations: number; other: Partial<{ [key in string]: number }> }
